version: '3'
services:
    frontend:
        restart: unless-stopped
        image: staticfloat/nginx-certbot
        ports:
            - 80:80/tcp
            - 443:443/tcp
        environment:
            CERTBOT_EMAIL: pymanuz@gmail.com
            # variable names are space-separated
            ENVSUBST_VARS: FQDN
            FQDN: askaraliev.uz
        volumes:
          - ./app:/usr/share/nginx/html
          - ./conf.d:/etc/nginx/user.conf.d
          - letsencrypt:/etc/letsencrypt
volumes:
    letsencrypt:

